[build]
  publish = "dist"
  command = "npm run build"

[build.environment]
  # These VITE_* are public config; omit them from secret scanning
  SECRETS_SCAN_OMIT_KEYS = "VITE_API_URL,VITE_MSAL_CLIENT_ID,VITE_MSAL_TENANT_ID"
  # Omit build output and test/mocks from scanning
  SECRETS_SCAN_OMIT_PATHS = "dist/**,src/**/__tests__/**,src/__mocks__/**"
  # Use Netlify proxy by default in production builds
  VITE_API_URL = "/api"

[[redirects]]
  from = "/api/*"
  to   = "https://walrus-app-z3a9a.ondigitalocean.app/api/:splat"
  status = 200
  force  = true

[[redirects]]
  from = "/*"
  to   = "/index.html"
  status = 200
