import { getUsers, deleteUser, createUser, updateUser, getPaginatedUser, getUserById } from "@/api/endpoints";
import { getProsjekter, deleteProsjekt, createProsjekt, updateProsjekt, getPaginatedProsjekt, getProsjektById } from "@/api/endpoints";
import { getEnheter, deleteEnhet, createEnhet, updateEnhet, getPaginatedEnhet, getEnhetById } from "@/api/endpoints";
import { getEmner, deleteEmne, createEmne, updateEmne, getPaginatedEmne, getEmneById } from "@/api/endpoints";
import {
  getVurderinger,
  deleteVurdering,
  createVurdering,
  updateVurdering,
  getPaginatedVurdering,
  getVurderingById,
} from "@/api/endpoints";
// Import the API helper
import {
  getKravpakker,
  deleteKravpakker,
  createKravpakker,
  updateKravpakker,
  getPaginatedKravpakker,
  getKravpakkerById,
} from "@/api/endpoints";

import { getStatus, deleteStatus, createStatus, updateStatus, getPaginatedStatus, getStatusById } from "@/api/endpoints";
import {
  getKravreferanseTyper,
  deleteKravreferanseType,
  createKravreferanseType,
  updateKravreferanseType,
  getPaginatedKravreferanseType,
  getKravreferanseTypeById,
} from "@/api/endpoints";

// Centralized model configurations
export const modelConfigs = {
  users: {
    queryKey: ["users"],
    queryFn: getPaginatedUser,
    getByIdFn: getUserById,
    createFn: createUser,
    updateFn: updateUser,
    deleteFn: deleteUser,
    modelPrintName: "bruker",
    fields: [
      { name: "navn", label: "Navn", type: "text", required: true },
      { name: "epost", label: "E-post", type: "email", required: true },
      {
        name: "rolle",
        label: "Rolle",
        type: "select",
        required: true,
        options: [
          { value: "user", label: "User" },
          { value: "admin", label: "Admin" },
        ],
      },
      { name: "enhetId", label: "Enhet", type: "enhetselect", required: true, placeholder: "Velg enhet" },
    ],
  },
  prosjekter: {
    queryKey: ["prosjekter"],
    queryFn: getPaginatedProsjekt,
    getByIdFn: getProsjektById,
    createFn: createProsjekt,
    updateFn: updateProsjekt,
    deleteFn: deleteProsjekt,
    modelPrintName: "Prosjekt",
    fields: [
      { name: "id", label: "ID", type: "number", hiddenIndex: true, hiddenEdit: true, hiddenCreate: true },
      {
        name: "prosjektnummer",
        label: "Prosjektnummer",
        type: "number",
        hiddenIndex: false,
        hiddenEdit: false,
        hiddenCreate: false,
        integer: true,
        min: 1,
        placeholder: "Skriv inn prosjektnummer",
      },
      { name: "navn", label: "Navn", required: true, type: "text", hiddenIndex: false, hiddenEdit: false, hiddenCreate: false },
      { name: "beskrivelse", label: "Beskrivelse", type: "text", hiddenIndex: false, hiddenEdit: false, hiddenCreate: false },
      {
        name: "enhetId",
        label: "Enhet",
        required: true,
        type: "enhetselect",
        hiddenIndex: false,
        hiddenEdit: false,
        hiddenCreate: false,
        placeholder: "Velg enhet",
      },
      {
        name: "userId",
        label: "User ID",
        type: "number",
        hiddenIndex: true,
        hiddenEdit: true,
        hiddenCreate: true,
        integer: true,
        min: 1,
        placeholder: "Velg bruker ID",
      },
      { name: "createdBy", label: "Created By", type: "number", hiddenIndex: true, hiddenEdit: true, hiddenCreate: true },
      { name: "updatedBy", label: "Updated By", type: "number", hiddenIndex: true, hiddenEdit: true, hiddenCreate: true },
    ],
  },
  enheter: {
    queryKey: ["enheter"],
    queryFn: getPaginatedEnhet,
    getByIdFn: getEnhetById,
    createFn: createEnhet,
    updateFn: updateEnhet,
    deleteFn: deleteEnhet,
    modelPrintName: "Organisasjonstilhørlighet",
    fields: [
      { name: "navn", label: "Navn", type: "text", required: true },
      { name: "beskrivelse", label: "Beskrivelse", type: "text", required: false },
      {
        name: "parentId",
        label: "Parent",
        type: "parentselect",
        required: false,
        hiddenIndex: true,
        placeholder: "Velg overordnet enhet",
      },
      { name: "level", label: "Nivå", type: "number", required: true, placeholder: "3 for FO, 2 for virksomhetsområde, 1 for firma" },
      {
        name: "createdBy",
        label: "Opprettet av",
        type: "number",
        required: false,
        hiddenIndex: true,
        hiddenEdit: true,
        hiddenCreate: true,
      },
      {
        name: "updatedBy",
        label: "Opprettet av",
        type: "number",
        required: false,
        hiddenIndex: true,
        hiddenEdit: true,
        hiddenCreate: true,
      },
      {
        name: "parentName",
        label: "Parent Name",
        type: "text",
        required: false,
        computed: (row) => (row.parent && row.parent.navn ? row.parent.navn : "N/A"),
        hiddenIndex: true,
        hiddenEdit: true,
        hiddenCreate: true,
      },
    ],
  },
  emner: {
    queryKey: ["emner"],
    queryFn: getPaginatedEmne,
    getByIdFn: getEmneById,
    createFn: createEmne,
    updateFn: updateEmne,
    deleteFn: deleteEmne,
    modelPrintName: "emne",
    fields: [
      {
        name: "tittel",
        label: "Tittel",
        type: "text",
        required: true,
      },
      {
        name: "beskrivelse",
        label: "Beskrivelse",
        type: "text",
        required: false,
      },
      {
        name: "enhetId",
        label: "EnhetId",
        type: "number",
        required: false,
        type: "enhetselect",
        hiddenIndex: true,
        hiddenEdit: true,
        hiddenCreate: true,
      },
      {
        name: "createdBy",
        label: "CreatedBy",
        type: "number",
        required: false,
        hiddenIndex: true,
        hiddenEdit: true,
        hiddenCreate: true,
        type: "userselect",
      },
      {
        name: "updatedBy",
        label: "UpdatedBy",
        type: "number",
        required: false,
        hiddenIndex: true,
        hiddenEdit: true,
        hiddenCreate: true,
        type: "userselect",
      },
    ],
  },
  status: {
    queryKey: ["status"],
    queryFn: getPaginatedStatus,
    getByIdFn: getStatusById,
    createFn: createStatus,
    updateFn: updateStatus,
    deleteFn: deleteStatus,
    modelPrintName: "status",
    fields: [
      {
        name: "navn",
        label: "Navn",
        type: "text",
        required: true,
      },
      {
        name: "sortIt",
        label: "Rekkefølge",
        type: "number",
        required: true,
      },
      {
        name: "enhetId",
        label: "EnhetId",
        type: "number",
        required: false,
        type: "enhetselect",
        hiddenIndex: true,
        hiddenEdit: true,
        hiddenCreate: true,
      },
      {
        name: "createdBy",
        label: "CreatedBy",
        type: "number",
        required: false,
        hiddenIndex: true,
        hiddenEdit: true,
        hiddenCreate: true,
        type: "userselect",
      },
      {
        name: "updatedBy",
        label: "UpdatedBy",
        type: "number",
        required: false,
        hiddenIndex: true,
        hiddenEdit: true,
        hiddenCreate: true,
        type: "userselect",
      },
    ],
  },
  vurderinger: {
    queryKey: ["vurderinger"],
    queryFn: getPaginatedVurdering,
    getByIdFn: getVurderingById,
    createFn: createVurdering,
    updateFn: updateVurdering,
    deleteFn: deleteVurdering,
    modelPrintName: "vurdering",
    fields: [
      {
        name: "navn",
        label: "Navn",
        type: "text",
        required: true,
      },
      {
        name: "sortIt",
        label: "Rekkefølge",
        type: "number",
        required: true,
      },
      {
        name: "enhetId",
        label: "EnhetId",
        type: "number",
        required: false,
        type: "enhetselect",
        hiddenIndex: true,
        hiddenEdit: true,
        hiddenCreate: true,
      },
      {
        name: "createdBy",
        label: "CreatedBy",
        type: "number",
        required: false,
        hiddenIndex: true,
        hiddenEdit: true,
        hiddenCreate: true,
        type: "userselect",
      },
      {
        name: "updatedBy",
        label: "UpdatedBy",
        type: "number",
        required: false,
        hiddenIndex: true,
        hiddenEdit: true,
        hiddenCreate: true,
        type: "userselect",
      },
    ],
  },

  kravpakker: {
    queryKey: ["kravpakker"],
    queryFn: getPaginatedKravpakker,
    getByIdFn: getKravpakkerById,
    createFn: createKravpakker,
    updateFn: updateKravpakker,
    deleteFn: deleteKravpakker,
    modelPrintName: "kravpakker",
    fields: [
      {
        name: "tittel",
        label: "Tittel",
        type: "text",
        required: true,
      },
      {
        name: "beskrivelse",
        label: "Beskrivelse",
        type: "text",
        required: false,
      },
      {
        name: "enhetId",
        label: "EnhetId",
        type: "number",
        required: true,
        type: "enhetselect",
      },
      {
        name: "createdBy",
        label: "CreatedBy",
        type: "number",
        required: false,
        hiddenIndex: true,
        hiddenEdit: true,
        hiddenCreate: true,
        type: "userselect",
      },
      {
        name: "updatedBy",
        label: "UpdatedBy",
        type: "number",
        required: false,
        hiddenIndex: true,
        hiddenEdit: true,
        hiddenCreate: true,
        type: "userselect",
      },
    ],
  },
};

// Helper function to get config by model type
export function getModelConfig(modelType) {
  return modelConfigs[modelType];
}
