import { getFagomrader, deleteFagomrade, createFagomrade, updateFagomrade, getPaginatedFagomrade, getFagomradeById } from "@/api/endpoints";

export const fagomrade = {
  queryKey: ["fagomrader"],
  queryFn: getPaginatedFagomrade,
  getByIdFn: getFagomradeById,
  createFn: createFagomrade,
  updateFn: updateFagomrade,
  deleteFn: deleteFagomrade,
  title: "Fagomrader",
  desc: "Håndter fagomrader",
  modelPrintName: "Fagomrade",
  newButtonLabelText: "Ny fagomrade",
  fields: [
    {
      name: "tittel",
      label: "Tittel",
      type: "text",
      required: true,
    },
    {
      name: "beskrivelse",
      label: "Beskrivelse",
      type: "text",
      required: false,
    },
    {
      name: "icon",
      label: "Ikon",
      type: "icon",
      required: false,
    },
    {
      name: "color",
      label: "Farge",
      type: "color",
      required: false,
    },
    {
      name: "sortIt",
      label: "SortIt",
      type: "number",
      required: false,
    },
    {
      name: "enhetId",
      label: "EnhetId",
      type: "number",
      required: false,
      type: "enhetselect",
      hiddenIndex: true,
      hiddenEdit: true,
      hiddenCreate: true,
    },
    {
      name: "createdBy",
      label: "CreatedBy",
      type: "number",
      required: false,
      hiddenIndex: true,
      hiddenEdit: true,
      hiddenCreate: true,
      type: "userselect",
    },
    {
      name: "updatedBy",
      label: "UpdatedBy",
      type: "number",
      required: false,
      hiddenIndex: true,
      hiddenEdit: true,
      hiddenCreate: true,
      type: "userselect",
    },
  ],
};
