// Generated model config for Files
import { getFiles, deleteFile, createFile, updateFile, getPaginatedFiles, getFileById } from "@/api/endpoints";

export const files = {
  queryKey: ["files"],
  queryFn: getPaginatedFiles,
  getByIdFn: getFileById,
  createFn: createFile,
  updateFn: updateFile,
  deleteFn: deleteFile,
  modelPrintName: "files",
  title: "Filer",
  desc: "beskrivelse ...",
  modelPrintName: "files",
  newButtonLabel: "Ny files",
  fields: [
    {
      name: "fileName",
      label: "FileName",
      type: "text",
      required: true,
    },
    {
      name: "fileType",
      label: "FileType",
      type: "text",
      required: true,
    },
    {
      name: "fileSize",
      label: "FileSize",
      type: "number",
      required: true,
    },
    {
      name: "digitalOceanUrl",
      label: "DigitalOceanUrl",
      type: "text",
      required: true,
    },
    {
      name: "digitalOceanKey",
      label: "DigitalOceanKey",
      type: "text",
      required: true,
    },
    {
      name: "fileUid",
      label: "FileUid",
      type: "text",
      required: true,
    },
    {
      name: "relatedModelType",
      label: "RelatedModelType",
      type: "text",
      required: false,
    },
    {
      name: "relatedModelId",
      label: "RelatedModelId",
      type: "number",
      required: false,
    },
    {
      name: "isPublic",
      label: "IsPublic",
      type: "text",
      required: true,
    },
    {
      name: "description",
      label: "Description",
      type: "text",
      required: false,
    },
    {
      name: "hasThumbnail",
      label: "HasThumbnail",
      type: "text",
      required: true,
    },
    {
      name: "thumbnailUrl",
      label: "ThumbnailUrl",
      type: "text",
      required: false,
    },
    {
      name: "thumbnailKey",
      label: "ThumbnailKey",
      type: "text",
      required: false,
    },
    {
      name: "enhetId",
      label: "EnhetId",
      type: "number",
      required: true,
      type: "enhetselect",
    },
    {
      name: "createdBy",
      label: "CreatedBy",
      type: "number",
      required: true,
      hiddenIndex: true,
      hiddenEdit: true,
      hiddenCreate: true,
      type: "userselect",
    },
    {
      name: "updatedBy",
      label: "UpdatedBy",
      type: "number",
      required: false,
      hiddenIndex: true,
      hiddenEdit: true,
      hiddenCreate: true,
      type: "userselect",
    },
  ],
};
