import { getProsjekter, deleteProsjekt, createProsjekt, updateProsjekt, getPaginatedProsjekt, getProsjektById } from "@/api/endpoints";

export const prosjektModel = {
  queryKey: ["prosjekter"],
  queryFn: getPaginatedProsjekt,
  getByIdFn: getProsjektById,
  createFn: createProsjekt,
  updateFn: updateProsjekt,
  deleteFn: deleteProsjekt,
  modelPrintName: "Prosjekt",
  fields: [
    { name: "id", label: "ID", type: "number", hiddenIndex: true, hiddenEdit: true, hiddenCreate: true },
    {
      name: "prosjektnummer",
      label: "Prosjektnummer",
      type: "number",
      hiddenIndex: false,
      hiddenEdit: false,
      hiddenCreate: false,
      integer: true,
      min: 1,
      placeholder: "Skriv inn prosjektnummer",
    },
    { name: "navn", label: "Navn", required: true, type: "text", hiddenIndex: false, hiddenEdit: false, hiddenCreate: false },
    { name: "beskrivelse", label: "Beskrivelse", type: "text", hiddenIndex: false, hiddenEdit: false, hiddenCreate: false },
    {
      name: "enhetId",
      label: "Enhet",
      required: true,
      type: "enhetselect",
      hiddenIndex: false,
      hiddenEdit: false,
      hiddenCreate: false,
      placeholder: "Velg enhet",
    },
    {
      name: "userId",
      label: "User ID",
      type: "number",
      hiddenIndex: true,
      hiddenEdit: true,
      hiddenCreate: true,
      integer: true,
      min: 1,
      placeholder: "Velg bruker ID",
    },
    { name: "createdBy", label: "Created By", type: "number", hiddenIndex: true, hiddenEdit: true, hiddenCreate: true },
    { name: "updatedBy", label: "Updated By", type: "number", hiddenIndex: true, hiddenEdit: true, hiddenCreate: true },
  ],
};
