export const fields = [
  {
    name: "tiltakUID",
    label: "Prosjekt Tiltak UID",
    type: "text",
    required: false,
    disabled: true,
    field_info: "Unik identifikator for prosjekttiltaket (genereres automatisk som GPT + ID)",
    show_in_list: true,
    show_in_form: true,
  },
  {
    name: "tittel",
    label: "Tittel",
    type: "text",
    required: true,
    field_info: "En kort, beskrivende tittel for prosjekttiltaket. Bør være spesifikk og lett å forstå.",
  },
  {
    name: "beskrivelse",
    label: "Beskrivelse",
    type: "basicrichtext",
    required: false,
    placeholder: "Beskriv prosjekttiltaket i detalj...",
    field_info: "Detaljert beskrivelse av prosjekttiltaket med grunnleggende formatering (fet, kursiv, understreking, overskrifter).",
    hiddenIndex: true,
  },
  {
    name: "implementasjon",
    label: "Implementasjon",
    type: "richtext",
    required: false,
    placeholder: "Legg til informasjon om hvordan prosjekttiltaket skal implementeres...",
    field_info: "Rik tekst med støtte for formatering, lenker, tabeller og bilder. Lim inn bilder direkte fra utklippstavlen.",
    suppressIndex: true, // Don't include this rich text field in index/list views
    hiddenIndex: true,
  },
  {
    name: "tilbakemelding",
    label: "Tilbakemelding",
    type: "richtext",
    required: false,
    placeholder: "Legg til tilbakemelding på prosjekttiltaket...",
    field_info: "Rik tekst med støtte for formatering, lenker, tabeller og bilder for tilbakemelding.",
    suppressIndex: true, // Don't include this rich text field in index/list views
    hiddenIndex: true,
  },
  {
    name: "beskrivelseSnippet",
    label: "Beskrivelse",
    type: "text",
    required: false,
    suppressIndex: false,
    hiddenCreate: true,
    hiddenEdit: true,
    truncate: 20,
  },
  {
    name: "implementasjonSnippet",
    label: "Implementasjon",
    type: "text",
    required: false,
    suppressIndex: false,
    hiddenCreate: true,
    hiddenEdit: true,
    truncate: 20,
  },
  {
    name: "tilbakemeldingSnippet",
    label: "Tilbakemelding",
    type: "text",
    required: false,
    suppressIndex: false,
    hiddenCreate: true,
    hiddenEdit: true,
    truncate: 20,
  },
  {
    name: "merknad",
    label: "Merknad",
    type: "text",
    required: false,
    field_info: "Merknad til prosjekttiltaket",
    hiddenIndex: true,
  },
  {
    name: "obligatorisk",
    label: "Obligatorisk",
    type: "bool",
    required: false,
    default: false,
  },
  {
    name: "prioritet",
    label: "Prioritet",
    type: "prioritetselect",
    required: false,
    defaultValue: 15,
  },
  {
    name: "givenOrder",
    label: "Rekkefølge",
    type: "number",
    required: false,
    defaultValue: 300,
    field_info: "Muliggjør sortering av prosjekttiltak",
  },
  {
    name: "parentId",
    label: "Overordnet prosjekttiltak",
    type: "prosjektTiltakselect",
    required: false,
    field_info:
      "Velg et overordnet prosjekttiltak hvis dette tiltaket er et undertiltak. Systemet forhindrer at tiltak med egne undertiltak kan velges som foreldre for å unngå hierarkiproblemer.",
  },
  {
    name: "generalTiltakId",
    label: "Tilknyttet generelt tiltak",
    type: "tiltakselect",
    required: false,
    field_info: "Velg hvilket generelle tiltak dette prosjekt-spesifikke tiltaket er tilknyttet",
  },
  {
    name: "vurderingId",
    label: "Vurdering",
    type: "vurderingselect",
    required: false,
  },
  {
    name: "statusId",
    label: "Status",
    type: "statusselect",
    required: false,
  },
  {
    name: "emneId",
    label: "Emne",
    type: "emneselect",
    required: false,
    field_info: "Velg hvilket emne prosjekttiltaket tilhører",
  },
  {
    name: "enhetId",
    label: "Enhet",
    type: "enhetselect",
    required: false,
    defaultValue: "USER_ENHET_ID", // Special marker for user's enhetId
  },
  {
    name: "createdBy",
    label: "Opprettet av",
    type: "userselect",
    required: false,
    hiddenIndex: true,
    hiddenEdit: true,
    hiddenCreate: true,
  },
  {
    name: "updatedBy",
    label: "Oppdatert av",
    type: "userselect",
    required: false,
    hiddenIndex: true,
    hiddenEdit: true,
    hiddenCreate: true,
  },
  {
    name: "prosjektKrav",
    label: "Tilknyttet prosjektkrav",
    type: "multiselect",
    entityType: "prosjektKrav",
    required: false,
    field_info: "Velg hvilke prosjektkrav dette tiltaket adresserer eller oppfyller",
    suppressIndex: true, // Don't include this many-to-many relationship in index views
  },
  {
    name: "files",
    label: "Vedlegg",
    type: "fileupload",
    required: false,
    field_info: "Last opp dokumenter, bilder eller andre filer knyttet til dette prosjekttiltaket",
    hiddenIndex: true, // Don't show in list view
    suppressIndex: true, // Don't include in index views
  },
];
